##
# FLOW3 subroutes
#
-
  name: 'Gucken.Org'
  uriPattern: '<GuckenOrgSubRoutes>'
  defaults:
    '@package':    'Org.Gucken.Events'    
    '@format': 'html'  
  subRoutes:
    GuckenOrgSubRoutes:
      package: Org.Gucken.Events
#-
#  name: 'FLOW3'
#  uriPattern: '<FLOW3Subroutes>'
#  defaults:
#    '@format': 'html'
#  subRoutes:
#    FLOW3Subroutes:
#      package: TYPO3.FLOW3
