#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #


TYPO3:
  FLOW3:
    security:
      cryptography:
        BCryptHashingStrategy:
          cost: 10
        
    
    persistence:
     backendOptions:
      driver: 'pdo_mysql'
      dbname: 'flow3'   # adjust to your database name
      user: 'root'        # adjust to your database user
      password: 'r4IDunzL'        # adjust to your database password
      host: '127.0.0.1'   # adjust to your database host
      path: '127.0.0.1'   # adjust to your database host
      port: 3306
      doctrine:
       # If you have APC, you should consider using it for Production,
       # also MemcacheCache and XcacheCache exist.
#        cacheImplementation: 'Doctrine\Common\Cache\ApcCache'
       # when using MySQL and UTF-8, this should help with connection encoding issues
        dbal:
          sessionInitialization: 'SET NAMES utf8 COLLATE utf8_unicode_ci'
  # On Windows, you might need to uncomment the following line and specify
  # the location of the PHP binary manually.
  #  core:
  #    phpBinaryPathAndFilename: 'C:/path/to/php.exe'
Org:
  Gucken:
    Events:
      view: bielefeld